// <auto-generated />
namespace m.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class blank : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(blank));
        
        string IMigrationMetadata.Id
        {
            get { return "201304101041198_blank"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
