// <auto-generated />
namespace m.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig_employee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_employee));
        
        string IMigrationMetadata.Id
        {
            get { return "201304080742476_mig_employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
